import { CssVarsProvider } from '@mui/joy/styles'
import Box from '@mui/joy/Box'
import CssBaseline from '@mui/joy/CssBaseline'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'စားလို့ရလား ?',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssVarsProvider disableTransitionOnChange >
          <CssBaseline />
          <Box
            sx={{
              height: '100vh',
              overflowY: 'scroll',
              scrollSnapType: 'y mandatory',
              '& > div': {
                scrollSnapAlign: 'start',
              },
            }}
          >
            {children}
          </Box>
        </CssVarsProvider>
      </body>
    </html>
  )
}
